spring:
  application:
    name: molodcentertelegrambot
  config:
    import: "classpath:messages.yml"
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    long-polling:
      drop-pending-on-start: true

app:
  user-action-cooldown: "1000" # в мілісекундах
  redis-live-time: "900000" # в мілісекундах

permissions: # з якого рівня адміністратору можна робити дії
  create-youth-centers: 8
  change-user-roles: 6
  control-youth-centers: 5 # з якого рангу адмін може змінювати категорії і події молодіжних центрів

user-roles:
  change-user-roles: 10
  change-categories: 6

servers:
  molodcenter: "localhost:8081"
  molodcenteruserservice: "localhost:8082"