spring:
  application:
    name: molodcentertelegrambot
  config:
    import: "classpath:messages.yml"
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    long-polling:
      drop-pending-on-start: true

app:
  user-action-cooldown: "1000" # в мілісекундах
  redis-live-time: "900000" # в мілісекундах

permissions: # з якого рівня адміністратору можна робити дії
  create-and-modify-youth-centers: 5

servers:
  molodcenter: "localhost:8081"
  molodcenteruserservice: "localhost:8082"